config/routes.rb
Bunyan::Engine.routes.draw do

	resources	:client_admin
	resources 	:event_admin
	
end

app/models/bunyan/application_record.rb
module Bunyan
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/bunyan/client.rb
require 'user_agent_parser'
require 'browser'

module Bunyan
	class Client < ApplicationRecord

		belongs_to 	:user, optional: true

		has_many 	:events


		def city
			self.ip_city
		end
		def city=(val)
			self.ip_city = val
		end

		def state
			self.ip_region
		end
		def state=(val)
			self.ip_region = val
		end

		def country
			self.ip_country_name
		end
		def country=(val)
			self.ip_country_name = val
		end

		def self.create_from_options( options )
			# don't create client if device not cookied
			raise "No uuid!!!" unless options[:uuid].present?
			return false unless options[:uuid].present?

			client = self.new( uuid: options[:uuid] )
			client.ip = options[:ip]
			client.user_agent = options[:user_agent]
			client.country = options[:country]
			client.state = options[:state]
			client.city = options[:city]

			client.user = options[:user]

			client.properties 	= options[:properties]

			client.campaign_source = options[:campaign_source]
			client.campaign_medium = options[:campaign_medium]
			client.campaign_name = options[:campaign_name]
			client.campaign_term = options[:campaign_term]
			client.campaign_content = options[:campaign_content]
			client.campaign_cost = options[:campaign_cost]

			client.partner_source = options[:partner_source]
			client.partner_id = options[:partner_id]

			client.referrer_url = options[:referrer_url]
			client.referrer_host = options[:referrer_host]
			client.referrer_path = options[:referrer_path]
			client.referrer_params = options[:referrer_params]
			if options[:referrer_url].present?
				begin
					uri = URI( options[:referrer_url] )
					client.referrer_host ||= uri.host
					client.referrer_path ||= uri.path
					client.referrer_params ||= uri.query
				rescue URI::InvalidURIError => e
				end
			end

			client.lander_url = options[:page_url]
			client.lander_host = options[:page_host]
			client.lander_path = options[:page_path]
			client.lander_params = options[:page_params]
			if options[:page_url].present?
				begin
					uri = URI( options[:page_url] )
					client.lander_host ||= uri.host
					client.lander_path ||= uri.path
					client.lander_params ||= uri.query
				rescue URI::InvalidURIError => e
				end
			end

			if options[:user_agent].present?
				user_agent = UserAgentParser.parse options[:user_agent]
				browser = Browser.new options[:user_agent]

				# # don't record anything for bots
				# raise "Got a Bot: #{browser.bot.name}" unless browser.bot.name.blank?

				# TODO - change to whitelist of NON-loggable bots
				# e.g.:
				if Bunyan.log_bots
					return false if browser.bot.name =~ Bunyan.bot_blacklist
				end

				client.is_bot = browser.bot.name.present?

				client.browser_family					= user_agent.family
				client.browser_version					= user_agent.version.to_s
				client.os_name							= user_agent.os.try(:name)
				client.os_version						= user_agent.os.version
				client.device_type						= 'tablet' if browser.device.try(:tablet?)
				client.device_type						= 'mobile' if browser.device.try(:mobile?)
				client.device_type						= 'tv' if browser.device.try(:tv?)
				client.device_type						= 'console' if browser.device.console?
				client.device_family					= user_agent.device.try(:family)
				client.device_brand						= user_agent.device.try(:brand)
				client.device_model						= user_agent.device.try(:model)
			end


			client.save

			return client

		end

		def update_from_options( options = {} )

			self.user = options[:user] if options[:user].present? && self.user != options[:user]


			self.last_campaign_source = options[:campaign_source]
			self.last_campaign_medium = options[:campaign_medium]
			self.last_campaign_name = options[:campaign_name]
			self.last_campaign_term = options[:campaign_term]
			self.last_campaign_content = options[:campaign_content]
			self.last_campaign_cost = options[:campaign_cost]

			self.last_partner_source = options[:partner_source]
			self.last_partner_id = options[:partner_id]

			self.last_referrer_url = options[:referrer_url]
			self.last_referrer_host = options[:referrer_host]
			self.last_referrer_path = options[:referrer_path]
			self.last_referrer_params = options[:referrer_params]
			if options[:referrer_url].present?
				begin
					uri = URI( options[:referrer_url] )
					self.last_referrer_host ||= uri.host
					self.last_referrer_path ||= uri.path
					self.last_referrer_params ||= uri.query
				rescue URI::InvalidURIError => e
				end
			end

			self.last_lander_url = options[:page_url]
			self.last_lander_host = options[:page_host]
			self.last_lander_path = options[:page_path]
			self.last_lander_params = options[:page_params]
			if options[:page_url].present?
				begin
					uri = URI( options[:page_url] )
					self.last_lander_host ||= uri.host
					self.last_lander_path ||= uri.path
					self.last_lander_params ||= uri.query
				rescue URI::InvalidURIError => e
				end
			end

			self.last_landed_at = [ (options[:created_at] || Time.now), self.last_landed_at ].max if self.last_landed_at.present?
			self.last_landed_at ||= (options[:created_at] || Time.now)


			self.save

		end


		def to_s
			user = self.user || 'Anonymous'
			"#{self.id} #{user}'s #{self.device_type} #{self.device_type} #{os_name} #{os_version} #{browser_family} #{browser_version}"
		end
	end
end

app/models/bunyan/event.rb
module Bunyan
	class Event < ApplicationRecord

		belongs_to 		:client, optional: true
		belongs_to 		:target_obj, polymorphic: true, optional: true
		belongs_to 		:user, optional: true


		def self.create_from_options( options )
			event_attributes = options[:event_attributes] || {}

			# TODO check for and reject duplicate events
			ttl = options[:ttl] || Bunyan.default_ttl
			if options[:client] && Event.where( client: options[:client], name: options[:name], page_url: options[:page_url] ).where( 'updated_at > :t', t: ttl.ago ).present?
				#dup_event.touch( :updated_at )
				return false
			end

			event_attributes.merge!(
				name: options[:name],
				client: options[:client],
				user: options[:user],
				target_obj_type: options[:target_obj].try( :class ).try( :base_class ).try( :name ),
				target_obj_id: options[:target_obj].try( :id ),
				category: options[:category],
				content: options[:content],
				value: options[:value]
			)

			event = self.new(event_attributes)

			event.created_at = options[:created_at] if options[:created_at].present?

			event.campaign_source = options[:campaign_source]
			event.campaign_medium = options[:campaign_medium]
			event.campaign_name = options[:campaign_name]
			event.campaign_term = options[:campaign_term]
			event.campaign_content = options[:campaign_content]
			event.campaign_cost = options[:campaign_cost]

			event.cart_id = options[:cart_id] if event.respond_to? :cart_id

			event.partner_source = options[:partner_source]
			event.partner_id = options[:partner_id]

			event.referrer_url = options[:referrer_url]
			event.referrer_host = options[:referrer_host]
			event.referrer_path = options[:referrer_path]
			event.referrer_params = options[:referrer_params]
			if options[:referrer_url].present?
				begin
					uri = URI( options[:referrer_url] )
					event.referrer_host ||= uri.host
					event.referrer_path ||= uri.path
					event.referrer_params ||= uri.query
				rescue URI::InvalidURIError => e
				end
			end

			event.page_url = options[:page_url]
			event.page_host = options[:page_host]
			event.page_path = options[:page_path]
			event.page_params = options[:page_params]
			event.page_name = options[:page_name]

			if options[:page_url].present?
				begin
					uri = URI( options[:page_url] )
					event.page_host ||= uri.host
					event.page_path ||= uri.path
					event.page_params ||= uri.query
				rescue URI::InvalidURIError => e
				end
			end

			event.category = options[:category] || Bunyan.event_categories[options[:name] ]

			event.save

			return event

		end




		def to_s
			user = self.user || 'Anonymous'

			"#{user} #{content}"
		end

	end
end

app/models/bunyan/event_summary.rb
module Bunyan
	class EventSummary < ApplicationRecord
		
	end
end

app/controllers/bunyan/client_admin_controller.rb
module Bunyan
	class ClientAdminController < ApplicationAdminController


		def edit
			@client = Client.find( params[:id] )
		end

		def index
			@clients = Client.order( created_at: :desc ).page( params[:page] )
		end

	end
end

app/controllers/bunyan/concerns/application_controller_concern.rb
module Bunyan
	module Concerns

		module ApplicationControllerConcern
			extend ActiveSupport::Concern

			included do
				include Bunyan::ApplicationHelper
			end


			####################################################
			# Class Methods

			module ClassMethods

			end


			####################################################
			# Instance Methods


			protected

		end

	end
end

app/controllers/bunyan/event_admin_controller.rb
module Bunyan
	class EventAdminController < ApplicationAdminController 

		def index
			@events = Event.order( created_at: :desc ).page( params[:page] )
		end

		def edit
			@event = Event.find( params[:id] )	
		end
	end
end

app/helpers/bunyan/application_helper.rb
module Bunyan
	module ApplicationHelper

		def bunyan_system_log( opts={} )
			@event_service ||= Bunyan.event_service_class_name.constantize.new

			# Merge options aliases
			opts[:name] ||= opts[:event] || opts[:event_name]
			opts[:target_obj] ||= opts[:on] || opts[:target]

			@event_service.log_event( opts )
		end

		def bunyan_merge_request_options!( opts = {} )
			# Set all the contextual values contained as
			# part of the request. params, headers, users, etc

			opts[:client_uuid] =				opts[:client_uuid].presence || cookies[:clientuuid].presence
			opts[:user] ||= 					current_user
			opts[:user_agent] ||=				request.user_agent
			opts[:page_name] ||=				@page_meta[:title]
			opts[:country] ||=					request.headers['CF-IPCountry']
			opts[:ip] ||=						request.headers['CF-Connecting-IP'] || request.remote_ip
			opts[:campaign_source] ||=			params[:utm_source]
			opts[:campaign_medium] ||=			params[:utm_medium]
			opts[:campaign_term] ||=			params[:utm_term]
			opts[:campaign_content] ||=			params[:utm_content]
			opts[:campaign_name] ||=			params[:utm_campaign]
			opts[:referrer_url] ||=				request.referrer
			opts[:page_url] ||=					request.original_url

			opts
		end

		def bunyan_clientize( opts={} )
			@event_service ||= Bunyan.event_service_class_name.constantize.new


			bunyan_merge_request_options!(opts)

			# Fetch or Create a universally unique random client id (uuid)
			client_uuid = opts[:client_uuid] = opts[:client_uuid].presence || SecureRandom.uuid

			@event_service.clientize( opts )

			cookies[:clientuuid] = {
				:value => client_uuid,
				:expires => 1.year.from_now
			}

			client_uuid
		end

		def bunyan_log( opts={} )
			@event_service ||= Bunyan.event_service_class_name.constantize.new

			# Merge options aliases and set event defaults
			opts[:name] ||= opts[:event] || opts[:event_name] || 'pageview' # default to pageview if no other event name specified
			opts[:target_obj] ||= opts[:on] || opts[:target]

			if opts[:name] == 'pageview'
				if opts[:target_obj].present?
					opts[:content] ||= "viewed #{request.method} #{request.path} for #{opts[:target_obj].to_s}"
				else
					opts[:content] ||= "viewed #{request.method} #{request.path}."
				end
			end

			bunyan_merge_request_options!(opts)

			@event_service.log_event( opts )

		end



	end
end

app/views/bunyan/client_admin/edit.html.haml
.container-fluid
	.row
		.col-xs-10
			%ul.breadcrumb
				%li
					%a{ href: '/admin' }
						Admin
				%li
					%a{ href: client_admin_index_path }
						Clients
				%li
					= @client.to_s
		.col-xs-2


	.row
		.col-xs-6
			%h2
				Events
			%table.table
				%thead
					%th
					%th
					%th
				%tbody
					- @client.events.each do |event|
						%tr
							%td
								%a{ href: edit_event_admin_path( event ) }
									= event.name
							%td
								= event.created_at
							%td
								= event.referrer_url



		.col-xs-6
			.well
				%h3
					Client Details
				%table.table

					%tr
						%td
							Device: 
						%td
							= @client.to_s

					%tr
						%td
							Created: 
						%td
							= @client.created_at

					%tr
						%td
							IP: 
						%td
							= @client.ip
					%tr
						%td
							UserAgent: 
						%td
							= @client.user_agent
					%tr
						%td
							Location
						%td
							= "#{@client.country}, #{@client.state}, #{@client.city}"
					%tr
						%td
							Referrer URL: 
						%td
							= @client.referrer_url
					%tr
						%td
							Referrer host: 
						%td
							= @client.referrer_host
					%tr
						%td
							Referrer Path: 
						%td
							= @client.referrer_path
					%tr
						%td
							Landing Page URL: 
						%td
							= @client.lander_url
					%tr
						%td
							Landing Page host: 
						%td
							= @client.lander_host
					%tr
						%td
							Landing Page Path: 
						%td
							= @client.lander_path

					%tr
						%td
							Campaign Source: 
						%td
							= @client.campaign_source
					%tr
						%td
							Campaign Medium: 
						%td
							= @client.campaign_medium
					%tr
						%td
							Campaign Term: 
						%td
							= @client.campaign_term
					%tr
						%td
							Campaign Content: 
						%td
							= @client.campaign_content
					%tr
						%td
							Campaign Name: 
						%td
							= @client.campaign_name
					%tr
						%td
							Campaign Cost: 
						%td
							= @client.campaign_cost
				

					%tr
						%td
							Device: 
						%td
							= @client.device_family
							= @client.device_brand
							= @client.device_model
					%tr
						%td
							OS: 
						%td
							= @client.os_name
							= @client.os_version

					%tr
						%td
							Browser: 
						%td
							= @client.browser_family
							= @client.browser_version

app/views/bunyan/client_admin/index.html.haml
.container-fluid
	.row
		.col-xs-10
			%ul.breadcrumb
				%li
					%a{ href: '/admin' }
						Admin
				%li
					Clients
		.col-xs-2
			
	.row{ style: 'margin-top: 0' }
		.col-xs-6
			= raw paginate @clients
		.col-xs-6
		

	.row
		.col-xs-12
			- if @clients.blank?
				.well
					%h3
						No Client Sessions Found
			- else

				%table.table.table-light.table-bordered
					%thead
						%th
							
						%th
							
						%th
							

					%tbody
						- @clients.each do |client|
							%tr
								%td
									= link_to client.to_s, edit_client_admin_path( client.id )
								%td
									= client.created_at
								
								%td
									= client.device_type
									= client.device_brand
									= client.device_model
									= client.device_family
		